### ISSUE TITLE
[BUG] InvalidURL: Failed to parse: <Response [200]>

### ISSUE THREAD

**Issue by KonerDev** [mpetazzoni/sseclient#28]
This is a part of my code but it doesn't work because I get an error:
## Code
```py
response = requests.post(url, data=json.dumps(body), headers=headers, stream=True)

client = sseclient.SSEClient(response)
for event in client.events():
    print("Got a new event from server")
    print(event.data)
```

## Error
```py
Traceback (most recent call last):
  File "C:\Users\Koner\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\url.py", line 425, in parse_url
    host, port = _HOST_PORT_RE.match(host_port).groups()  # type: ignore[union-attr]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'groups'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Koner\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 434, in prepare_url
    scheme, auth, host, port, path, query, fragment = parse_url(url)
                                                      ^^^^^^^^^^^^^^
  File "C:\Users\Koner\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\url.py", line 451, in parse_url        
    raise LocationParseError(source_url) from e
urllib3.exceptions.LocationParseError: Failed to parse: <Response [200]>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Dev\python\...\goconverted.py", line 33, in <module>
    response, status_code = doRequest(
                            ^^^^^^^^^^^
  File "C:\Dev\python\...\goconverted.py", line 25, in doRequest
    client = sseclient.SSEClient(response)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Koner\AppData\Local\Programs\Python\Python311\Lib\site-packages\sseclient.py", line 48, in __init__
    self._connect()
  File "C:\Users\Koner\AppData\Local\Programs\Python\Python311\Lib\site-packages\sseclient.py", line 56, in _connect
    self.resp = requester.get(self.url, stream=True, **self.requests_kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Koner\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Koner\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Koner\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 575, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Koner\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 486, in prepare_request 
    p.prepare(
  File "C:\Users\Koner\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "C:\Users\Koner\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 436, in prepare_url       
    raise InvalidURL(*e.args)
requests.exceptions.InvalidURL: Failed to parse: <Response [200]>
```

I think this is because the stream starts with `data:` and then sseclient thinks it is a URL and not a stream, but I could be wrong.

## Part of the data stream
```asciidoc
b'data: {"message": {"id": "3e96 ... 4d573f62", "error": null}\n\ndata: [DONE]\n\n'
```

**Comment by KonerDev** [comment]
Oh no, I found the error. I installed `sseclient`, but I should have installed `sseclient-py`.

**Comment by mpetazzoni** [comment]
Glad you found the issue; sorry about the name, `sseclient` already existed but was missing key functionality, which drove me to write this library.
